### ISSUE TITLE
Callback doesn't get called when using fake server

### ISSUE THREAD

**Issue by ddm** [cjohansen/sinon-qunit#1]
I am trying to use the fake server in a QUnit test suite using the following test:

``` javascript
test("Fake server is working",
    function () {
        var callback = this.spy();

        var server = this.sandbox.useFakeServer();
        server.respondWith("GET", "/myapp/users.json",
                           [200, { "Content-Type": "application/json" },
                            '[{ id: 123, name: "John" }]']);
        // Uncomment below to pass
        // sinon.stub(jQuery, "ajax").yieldsTo("success", {id: 123, name: "John"});

        $.getJSON("/myapp/users.json", callback)

        server.respond();

        ok(callback.calledOnce, "Callback was called once")
        ok(callback.calledWith({ id: 123, name: "John" }), "Callback was called with correct arguments");
    }
)
```

My initial guess was that the callback would be called upon server.respond() but unless I intercept the jQuery.ajax call explicitely (bypassing the fake server altogether) I can't get the intended behavior.

Am I missing something or  is this a bug?

**Comment by cjohansen** [comment]
The problem is that `getJSON` uses script tags to get JSON, not `XMLHttpRequest` objects. I guess maybe the adapter should deal with that, but in the meantime you have to stub the `getJSON` method; `sinon.stub(jQuery, "getJSON").yields(yourJson)`

**Comment by ddm** [comment]
Same goes for `jQuery.ajax` I guess, hence my comment in the test. 
Not a big deal but I liked the way the fake server allowed me to specify different response for different URLs. I'll just do something similar using a `jQuery.ajax` smarter stub.
Thanks for dropping by so fast BTW. And kudos for the fine work on Sinon.JS

**Comment by ddm** [comment]
The test below behaves as expected using sinon-1.0.0  (but fails with sinon-1.2.0):

``` javascript
test("Fake server is working", function () {
    var callback = this.spy();

    var server = this.sandbox.useFakeServer();
    server.respondWith("GET", "/myapp/users.json",
                       [200, { "Content-Type": "application/json" },
                        '[{ id: 123, name: "John" }]']);

    $.ajax({
        url: "/myapp/users.json",
        success: callback
    })

    server.respond();

    ok(callback.calledOnce, "Callback was called once")
    ok(callback.calledWith('[{ id: 123, name: "John" }]'), "Callback was called with correct arguments");
})
```

**Comment by cjohansen** [comment]
Hmm, I think my first comment was completely bogus. This isn't a JSON-P request, it's a regular ajax request. Sorry. Could you also try with Sinon 1.1.1? I might have broken something in yesterday's release... http://sinonjs.org/releases/sinon-1.1.1.js

**Comment by ddm** [comment]
I just tried 1.1.1 and the test fails as it did with 1.2.0. I'll dive into it to see if I can find the culprit...

**Comment by cjohansen** [comment]
Aha! Here's your problem: You're feeding in invalid JSON (property names aren't quoted). jQuery automatically tries to parse it (because of the `Content-Type`) and fails. Try adding an `error` callback ;)

**Comment by ddm** [comment]
Ok this is downright embarassing... I should have caught this before bugging you.

For the record, here is the passing test for sinon-1.2.0:

``` javascript
test("Fake server is working", function () {
    var callback = this.spy();

    var server = this.sandbox.useFakeServer();
    server.respondWith("GET", "/myapp/users.json",
                       [200, { "Content-Type": "application/json" },
                        '[{ "id": 123, "name": "John" }]']);

    $.ajax({
        url: "/myapp/users.json",
        success: callback
    })
    // Also works:
    // $.getJSON("/myapp/users.json",callback)

    server.respond();

    ok(callback.calledOnce, "Callback was called once")
    ok(callback.calledWith([{ id: 123, name: "John" }]), "Callback was called with correct arguments");
})
```

If you are using sinon-1.0.0, the last line should be:

``` javascript
ok(callback.calledWith('[{ "id": 123, "name": "John" }]'), "Callback was called with correct arguments");
```

Thanks again for taking the time to look into this. Hopefully this can serve as a reference for others...

Happy coding!

**Comment by hemabahirwani** [comment]
Hi, I am facing the same issue. The server is not intercepting any of the requests made; call back function not called 
Following is my code. Could you please help me with the same.

```
var successResponse={
'hello':'world',
'test2':'success'};

    describe("Testing API calls", function() {
      var server;
      var sinon = require('sinon');
      beforeEach(function() {

        server = sinon.fakeServer.create();
        server.autoRespond = true;
        server.autoRespondAfter = 0;
        server.respondWith("GET", "http://xx.xx.x.xx/abc/10/100",
                           [200, { "Content-Type": "application/json" },
                            JSON.stringify(successResponse)]);

      });
       console.log('fake server initialized');

      afterEach(function () {
        server.restore();
      });

      it("should fake a request", function () {
            var spy = sinon.spy();
            let myApi = new APIClass();
            myApi.getList(100,10,spy);    //making the API call 
            console.log(server.requests.length); //returns 0
            server.respond();
            expect(spy.calledOnce).toBe(true); //return false
            expect(spy.returned(sinon.match.same(successResponse)).toBe(true)); //returns false
       });
    });
```

**Comment by steve-taylor** [comment]
I don't think `autoRespond` actually works.
