### ISSUE TITLE
Assertion property: 'notCalled' returns undefined

### ISSUE THREAD

**Issue by ianneub** [cjohansen/sinon-qunit#2]
It seems that when stubbing out a function that the notCalled property is not being set.

Please see the following:

``` javascript
module("Bug?");
test("testing notCalled", 3, function(){
  this.stub(jQuery, "ajax");

  ok(jQuery.ajax.notCalled); // fails with: failed
  sinon.assert.notCalled(jQuery.ajax); // success with: notCalled
  equal(jQuery.ajax.callCount, 0); // success with: okay, Expected: 0
});
```

Any thoughts?

Thanks!

**Comment by cjohansen** [comment]
`sinon.assert.notCalled()` works, `spy.notCalled` isn't really a feature at this point. It makes sense to have though, so I made an issue on the Sinon repo to add it: https://github.com/cjohansen/Sinon.JS/issues/74
