### ISSUE TITLE
async tests never continue

### ISSUE THREAD

**Issue by absoludity** [cjohansen/sinon-qunit#3]
If I create a simple test module using the example async test:

``` javascript
module("Test async");

asyncTest("a test", function() {
  setTimeout(function(){
    ok(true, "always fine");
    start();
  }, 13);
});
```

saved as test/test_qunit.js and included in my html like this: http://paste.ubuntu.com/906759/

then the start() is never called and the test runner never completes. If I remove sinon-qunit from my html (line 8), the test completes as expected.

**Comment by cjohansen** [comment]
The problem is that the qunit-sinon adapter configures Sinon to fake timers by default. Disable by saying `this.clock.restore()` in a single test, or `sinon.config.useFakeTimers = false` before all tests

**Comment by trcarden** [comment]
Uhm this got me too. Can this be mentioned in the docs or perhaps a nonbreaking default for the adapter? 

Docs here don't seem to mention that by default the adapter breaks qunit asyncTests.
http://sinonjs.org/qunit/

**Comment by kylegibson-rldatix** [comment]
This was frustrating to debug.

**Comment by cjohansen** [comment]
I don't use QUnit, so if someone using it has better suggestions for defaults etc, feel free to submit a PR!
