### ISSUE TITLE
useFakeTimers enabled by default?

### ISSUE THREAD

**Issue by goligo** [cjohansen/sinon-qunit#6]
When embedding sinon-qunit.js, all usage of setTimeout in existing tests stops working, as the sinon-qunit.js enables fake timers by default. I don't see a good reason for doing so, I would prefer to chose to use fake timers when I need to.

**Comment by cjohansen** [comment]
It would be a breaking change, but I tend to agree. PR it? :)

**Comment by goligo** [comment]
Fixed.
